name: Build Desktop App

on:
  workflow_dispatch:

jobs:

  build_win:
    runs-on: build.app.win
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing rependencies
        run: npm i
        
      - name: Preparing source code
        run: npm run dev:bastyon
        
      - name: Building installer
        run: npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: |
            .\dist\BastyonSetup.exe
            .\dist\latest.yml

  build_macos:
    runs-on: build.app.macos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing rependencies
        run: npm i
        
      - name: Preparing source code
        run: npm run dev:bastyon
        
      - name: Preparing environment
        run: cp ../../../.app.env ./.env
        
      - name: Building installer
        run: npm run distm

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MacOS
          path: |
            .\dist\BastyonSetup.dmg
            .\dist\latest-mac.yml

  build_linux:
    runs-on: build.app.linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing rependencies
        run: npm i
        
      - name: Preparing source code
        run: npm run dev:bastyon
        
      - name: Building installer
        run: npm run distl

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: |
            .\dist\BastyonSetup.deb
            .\dist\Bastyon.AppImage
            .\dist\latest-linux.yml
