name: Deploy to Production

on:
  workflow_dispatch:
  push:
    tags: v*.*.*-web

jobs:
  build:
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run minimize:bastyon
        
      - name: Prepare archive
        run: |
          mkdir ~/dist
          rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ ~/dist
          cd ~/dist
          tar czf ~/bastyon.tgz .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bastyon.tgz
          path: ~/bastyon.tgz

  deploy:
    needs: build
    runs-on: [self_hosted, web_production, ${{ matrix.label }}]
    strategy:
      matrix:
        label: [prod1, prod2]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: bastyon.tgz
      - name: Unpack artifact
        run: tar xzf bastyon.tgz -C /docker/gui/
